[package]
name = "settings"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
dampen-core = { workspace = true }
dampen-iced = { workspace = true }
dampen-macros = { workspace = true }
iced = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
