[package]
name = "responsive"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
dampen-core = { workspace = true }
dampen-runtime = { workspace = true }
dampen-iced = { workspace = true }
iced = { workspace = true }

[[bin]]
name = "responsive"
path = "src/main.rs"
